version: 2
updates:
  # Enable version updates for Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase-if-necessary
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"