name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    # Run when Dockerfiles or related files change
    paths:
      - 'docker/**'
      - 'script/**'
      - 'alembic/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/docker-build-push.yml'
      - 'Makefile'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the images'
        required: false
        default: ''

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine version
        id: version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=$(date +'%Y%m%d')" >> $GITHUB_ENV
          fi

      - name: Build and push images
        run: |
          make push-images VERSION=$VERSION